apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
